name: fcsilmi_app
description: Application non-officielle de statistiques du FC Silmi.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  pie_chart: ^4.0.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true