name: fcsilmi_app
description: Application non-officielle de statistiques du FC Silmi.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  pie_chart: ^4.0.1
  infinite_scroll_pagination: ^2.3.0
  curved_navigation_bar: ^0.3.7
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/fcsilmi_old-white.png
    - assets/images/fcsilmi_logo.png